services:
  web-dev:
    build: .
    image: profile-web-dev
    container_name: profile-dev
    ports:
      - "${PORT}:80"
    environment:
      - ENVIRONMENT=dev
    restart: unless-stopped
    profiles:
      - dev
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-prod:
    build: .
    image: profile-web-prod
    container_name: profile-prod
    ports:
      - "${PORT}:80"
    environment:
      - ENVIRONMENT=prod
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s