services:
  web:
    build: .
    image: profile-web-${ENVIRONMENT}
    container_name: profile-${ENVIRONMENT}
    ports:
      - "${PORT}:80"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s