version: '3.8'

services:
  web:
    build: .
    container_name: profile-web
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-production}
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web-dev:
    build: .
    container_name: profile-web-dev
    ports:
      - "${DEV_PORT}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
    restart: unless-stopped
    profiles:
      - dev
    volumes:
      - ./src:/app/src:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s